spring:
  datasource:
    url: jdbc:mysql://localhost:3306/company
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Yennefer05!
  jpa:
    show-sql: true
  sql:
    init:
      mode: always