spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movieclub
    username: root
    password: Yennefer05!
  liquibase:
    contexts: prod
  web:
    resources:
      static-locations: classpath:/static/,file:///C:/Users/patry/Documents/GitHub/java-start-spring/project/uploads
app:
  storage:
    location: C:/Users/patry/Documents/GitHub/java-start-spring/project/uploads